SELECT 
   A.TABLE_CATALOG AS DBName,
   A.TABLE_SCHEMA AS "SCHEMA",
   A.TABLE_NAME AS "TABLE",
   B.COLUMN_NAME AS "COLUMN",
   IDENT_SEED (A.TABLE_NAME) AS Seed,
   IDENT_INCR (A.TABLE_NAME) AS Increment,
   IDENT_CURRENT (A.TABLE_NAME) AS Curr_Value,
   B.DATA_TYPE as "Type",
   Type_Limit = CASE lower (B.DATA_TYPE)
      WHEN 'bigint'
         THEN '9,223,372,036,854,775,807'
      WHEN 'int'
         THEN '2,147,483,647'
      WHEN 'smallint'
         THEN '32,767'
      WHEN 'tinyint'
         THEN '255'
      WHEN 'decimal'  
         THEN REPLICATE ('9', B.NUMERIC_PRECISION)
      WHEN 'numeric'  
         THEN REPLICATE ('9', B.NUMERIC_PRECISION)
      END,
   Utilized_Percentage = CAST(
      CASE lower(B.DATA_TYPE)
         WHEN 'bigint'
            THEN (CAST(IDENT_CURRENT(A.TABLE_NAME) AS FLOAT) / 9223372036854775807) * 100
         WHEN 'int'
            THEN (CAST(IDENT_CURRENT(A.TABLE_NAME) AS FLOAT) / 2147483647) * 100
         WHEN 'smallint'
            THEN (CAST(IDENT_CURRENT(A.TABLE_NAME) AS FLOAT) / 32767) * 100
         WHEN 'tinyint'
            THEN (CAST(IDENT_CURRENT(A.TABLE_NAME) AS FLOAT) / 255) * 100
         WHEN 'decimal'
            THEN (CAST(IDENT_CURRENT(A.TABLE_NAME) AS FLOAT) / CAST(REPLICATE('9', B.NUMERIC_PRECISION) AS FLOAT)) * 100
         WHEN 'numeric'
            THEN (CAST(IDENT_CURRENT(A.TABLE_NAME) AS FLOAT) / CAST(REPLICATE('9', B.NUMERIC_PRECISION) AS FLOAT)) * 100
      END AS DECIMAL(10,2))
FROM INFORMATION_SCHEMA.TABLES A, INFORMATION_SCHEMA.COLUMNS B
WHERE A.TABLE_CATALOG = B.TABLE_CATALOG 
   AND A.TABLE_SCHEMA = B.TABLE_SCHEMA 
   AND A.TABLE_NAME = B.TABLE_NAME 
   AND COLUMNPROPERTY(OBJECT_ID(B.TABLE_NAME), B.COLUMN_NAME, 'IsIdentity') = 1 
   AND OBJECTPROPERTY(OBJECT_ID(A.TABLE_NAME), 'TableHasIdentity') = 1 
   AND A.TABLE_TYPE = 'BASE TABLE'
ORDER BY 7 DESC;
